//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosovRPM_20
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCompound
    {
        public int ProductCode { get; set; }
        public int DetailCode { get; set; }
        public Nullable<int> DetailCount { get; set; }
    
        public virtual DetailDirectory DetailDirectory { get; set; }
        public virtual ProductDirectory ProductDirectory { get; set; }
    }
}
