//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosovRPM_20
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReleasePlan
    {
        public int ProductCode { get; set; }
        public Nullable<int> ProductCount { get; set; }
        public Nullable<int> WorkshopCode { get; set; }
    
        public virtual ProductDirectory ProductDirectory { get; set; }
        public virtual Workshop Workshop { get; set; }
    }
}
